- name: Copy hospital network interface config
  ansible.builtin.copy:
    src: netplan.yaml
    dest: /etc/netplan/60-hospital-network.yaml
  become: true
  when: '"ens6" is in ansible_interfaces'
  notify: Apply netplan

- name: Remove hospital network interface config
  ansible.builtin.file:
    path: /etc/netplan/60-hospital-network.yaml
    state: absent
  become: true
  when: '"ens6" is not in ansible_interfaces'
  notify: Apply netplan
