apiVersion: kubelet.config.k8s.io/v1alpha1
kind: CredentialProviderConfig
providers:
- name: ecr-credential-provider
  matchImages:
  - "*.dkr.ecr.ap-northeast-1.amazonaws.com"
  defaultCacheDuration: "18h"
  apiVersion: credentialprovider.kubelet.k8s.io/v1alpha1
